name: Schedule workflow

on:
  schedule:
    - cron:  '08 11 * * *'

jobs:
  TestJob:
    runs-on: ubuntu-latest

    steps:
    - name: Say hello at a certain hour
      run: echo "Hello, because it's time to do so!"
